name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main  # Replace with your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v2.2.1
